/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jFrame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
/**
 *
 * @author DELL
 */
public class signupPage extends javax.swing.JFrame {

    /**
     * Creates new form signupPage
     */
    public signupPage() {
        initComponents();
    }
    
    
   //methods to insert values into user table
public void insertSignupDetails(){
    String name=txt_username.getText();
    String pwd=txt_password.getText();
    String email=txt_email.getText();
    String contact=txt_contact.getText();
    
    try {
        Connection con=DBConnection.getConnection();
        String sql="insert into users(name,password,email,contact) values(?,?,?,?)";
        PreparedStatement pst=con.prepareStatement(sql);
        pst.setString(1,name);
        pst.setString(2,pwd);
        pst.setString(3,email);
        pst.setString(4,contact);
        
        int updatedRowCount=pst.executeUpdate();
        if(updatedRowCount>0){
            JOptionPane.showMessageDialog(this,"Recorded inserted successfully");
              LoginPage page = new LoginPage();
                page.setVisible(true);
                dispose();
        }else{
            JOptionPane.showMessageDialog(this,"Recorded insertion failure");
        }
        
    }catch(Exception e){
        e.printStackTrace();
    }
    }

 public boolean validateSignup(){
        String name = txt_username.getText();
        String pwd = txt_password.getText();
        String email = txt_email.getText();
        String contact = txt_contact.getText();
        
        if (name.equals("")) {
            JOptionPane.showMessageDialog(this, "please enter username");
            return false;
        }
        
        if (pwd.equals("")) {
            JOptionPane.showMessageDialog(this, "please enter password");
            return false;
        }
        
        if (email.equals("") || !email.matches("^.+@.+\\..+$")) {
            JOptionPane.showMessageDialog(this, "please enter valid email");
            return false;
        }
        
         if (contact.equals("")) {
            JOptionPane.showMessageDialog(this, "please enter contact number");
            return false;
        }
        
        return true;
    }
    
    //check duplicate users
    public boolean checkDuplicateUser(){
        String name = txt_username.getText();
        boolean isExist = false;
        
        try {
            Connection  con = DBConnection.getConnection();
           
            PreparedStatement pst = con.prepareStatement("select * from users where name = ?");
            pst.setString(1, name);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                isExist = true;
            }else{
                isExist = false;
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        return isExist;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signup1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        icoon = new javax.swing.JLabel();
        signup2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_contact = new app.bolivia.swing.JCTextField();
        txt_username = new app.bolivia.swing.JCTextField();
        txt_password = new app.bolivia.swing.JCTextField();
        txt_email = new app.bolivia.swing.JCTextField();
        btn_signup = new necesario.RSMaterialButtonCircle();
        btn_login = new necesario.RSMaterialButtonCircle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1400, 800));
        setPreferredSize(new java.awt.Dimension(1400, 800));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signup1.setBackground(new java.awt.Color(255, 255, 255));
        signup1.setPreferredSize(new java.awt.Dimension(900, 630));
        signup1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Welcome to the Library");
        signup1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 220, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("St.Vincent Pallotti College of Engineering,Nagpur");
        signup1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 480, 20));

        icoon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jFrame/icons/icons/digital-library-project.jpg"))); // NOI18N
        signup1.add(icoon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 720, 540));

        getContentPane().add(signup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 800));

        signup2.setBackground(new java.awt.Color(0, 102, 102));
        signup2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(51, 0, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Create New Account Here");
        signup2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 250, -1));

        jLabel4.setBackground(new java.awt.Color(51, 0, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SignUp Page");
        signup2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 230, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contact");
        signup2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 340, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Username");
        signup2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 340, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password");
        signup2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 330, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email");
        signup2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 340, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jFrame/icons/icons/icons8_Google_Mobile_50px.png"))); // NOI18N
        signup2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 50, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jFrame/icons/icons/icons8_Account_50px.png"))); // NOI18N
        signup2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 50, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jFrame/icons/icons/icons8_Secured_Letter_50px.png"))); // NOI18N
        signup2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 50, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jFrame/icons/icons/icons8_Secure_50px.png"))); // NOI18N
        signup2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 50, 50));

        txt_contact.setBackground(new java.awt.Color(0, 102, 102));
        txt_contact.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_contact.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_contact.setPhColor(new java.awt.Color(255, 255, 255));
        txt_contact.setPlaceholder("Enter the contact");
        signup2.add(txt_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 290, -1));

        txt_username.setBackground(new java.awt.Color(0, 102, 102));
        txt_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_username.setName(""); // NOI18N
        txt_username.setPhColor(new java.awt.Color(255, 255, 255));
        txt_username.setPlaceholder("Enter the username");
        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usernameFocusLost(evt);
            }
        });
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        signup2.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 290, -1));

        txt_password.setBackground(new java.awt.Color(0, 102, 102));
        txt_password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_password.setPhColor(new java.awt.Color(255, 255, 255));
        txt_password.setPlaceholder("Enter the password");
        signup2.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 290, -1));

        txt_email.setBackground(new java.awt.Color(0, 102, 102));
        txt_email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_email.setPhColor(new java.awt.Color(255, 255, 255));
        txt_email.setPlaceholder("Enter the email");
        signup2.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 290, -1));

        btn_signup.setBackground(new java.awt.Color(0, 51, 51));
        btn_signup.setText("SIGN UP");
        btn_signup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signupActionPerformed(evt);
            }
        });
        signup2.add(btn_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, 270, 80));

        btn_login.setBackground(new java.awt.Color(0, 51, 51));
        btn_login.setText("LOGIN");
        btn_login.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        signup2.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 640, 270, 80));

        getContentPane().add(signup2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 650, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void txt_btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_btnloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_btnloginActionPerformed

    private void txt_btnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_btnsignupActionPerformed
        // TODO add your handling code here:
        insertSignupDetails();
    }//GEN-LAST:event_txt_btnsignupActionPerformed

    private void txt_contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contactActionPerformed

    private void btn_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signupActionPerformed
         
        if (validateSignup() == true) {
            if (checkDuplicateUser() == false) {
                  insertSignupDetails();  
            }else{
               JOptionPane.showMessageDialog(this, "username already exist"); 
            }
                    
           
        }
        
       
    }//GEN-LAST:event_btn_signupActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusLost
        // TODO add your handling code here:
         if (checkDuplicateUser() == true) {
            JOptionPane.showMessageDialog(this, "username already exist");
        }
    }//GEN-LAST:event_txt_usernameFocusLost

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        LoginPage log = new LoginPage();
        log.setVisible(true);
        dispose();       
    }//GEN-LAST:event_btn_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signupPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private necesario.RSMaterialButtonCircle btn_login;
    private necesario.RSMaterialButtonCircle btn_signup;
    private javax.swing.JLabel icoon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel signup1;
    private javax.swing.JPanel signup2;
    private app.bolivia.swing.JCTextField txt_contact;
    private app.bolivia.swing.JCTextField txt_email;
    private app.bolivia.swing.JCTextField txt_password;
    private app.bolivia.swing.JCTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
